Restore `granularity` key in `annotated_groupbys`
Odoo will raise the following error when we try to show the `Sales` report:  

```
  File "/home/lubuntu/odoo-15.0/odoo/models.py", line 2144, in _read_group_fill_temporal
    granularity = first_a_gby['granularity']
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lubuntu/odoo-15.0/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/lubuntu/odoo-15.0/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'granularity'
```